CREATE TABLE IF NOT EXISTS filmes (
  idfilme INT PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(255) NOT NULL,
  descricao TEXT NOT NULL,
  ano INT NOT NULL);
  
INSERT INTO filme(nome, descricao, ano)
VALUES
('A Origem', 'Cobb é um talentoso ladrão: ele rouba os segredos mais escondidos nas profundezas do subconsciente durante o sono, quando o ser humano fica mais vulnerável. As habilidades raras de Cobb tranformam-no em uma pessoa valiosa no mundo da espionagem corporativa, mas também colocam todos os seus desejos na berlinda. A Origem representa uma trama totalmente nova no cinema. Um filme que será sempre atual.', 2010)
,('O Enigma de Outro Mundo','Um grupo de investigadores na Antártida se vê envolvido em um verdadeiro pesadelo numa estação polar norte-americana. O filme é realmente assustador, e é preciso dizer que foi feito sem ajuda do design gráfico. Um clássico do seu gênero.',1982)
,('Whiplash: Em Busca da Perfeição','Andrew sonha em ser um grande música. O melhor diretor de orquestra do país percebe seu potencial. O desejo de Andrew vira uma obsessão, e seu mentor desalmado continua pressionando-o até fazê-lo ultrapassar os limites das possibilidades humanas. ',2014)
,('O Silêncio dos Inocentes','Lançado há mais de 20 anos, o filme continua conquistando o público. A direção, atuações, trilha sonora... tudo é muito bom! Mostra uma história que nos prende e mantém nossa atenção na tela até os últimos segundos. Se encaixa perfeitamente na categoria de suspense psicológico.',1991)
,('Matrix','Filme revolucionário da história do cinema, e que continua atual. Não importa o quão difícil seja uma situação, o quão pequenas sejam suas chances de conseguir sucesso ou o preço a ser pago pela verdade, ainda assim valerá a pena lutar.', 1999)
,('Três Homens em Conflito','Em plena guerra civil, um vaqueiro misterioso, ótimo atirador, anda viajando pelo Velho Oeste. Não tem casa, nem amigos, não companheiros, até conhecer dois estranhos tão cínicos e desalmados quanto ele. O tempo passa voando quando você vê este filme, um verdadeiro clássico, digno de estar em sua coleção cinematográfica',1966 )
,('Cidade de Deus','Um dos maiores sucessos do cinema brasileiro, retrata o que acontece no decorrer de 30 anos em Cidade de Deus, comunidade do Rio de Janeiro. Lugar real, com histórias reais, com elenco escolhido entre os próprios moradores, com reações reais e uma linguagem muito direta. Realidade do começo ao fim. A ótima estreia de Seu Jorge no cinema.',2002)
,('12 Homens e uma Sentença','Este aparece em qualquer lista de melhores filmes. Um jovem é acusado de matar seu próprio pai, e pode ser condenado à cadeira elétrica. 12 membros do júri se reúnem para chegar a um veredito, se o homem é culpado ou não. É um filme que continua atual com o passar das décadas. Definitivamente, merece a nota máxima!',1957)
,('Histórias Cruzadas','Filme excelente sobre a difícil vida das mulheres de pele negra numa sociedade dominada pelos brancos, durante os anos 60. É um longa forte, honesto, autêntico e nada pretensioso. A trama é dinâmica e muito sentimental. Apesar de ser um pouco longo, você nem vê o tempo passar, pois fica imerso na história',2011)
,('Um Sonho de Liberdade','Um banqueiro de sucesso é acusado de matar sua esposa e o amante dela. Uma vez na prisão, chamada Shawshank, ele enfrenta a violência e o caos. Mas Andy começa a traçar um plano ousado para ficar livre. O filme é uma joia do cinema, é sempre possível voltar a assisti-lo sem se entediar. Atuação impecável de Morgan Freeman.',1994)
,('Knockin on Heavens Door','O destino cruza os caminhos dos protagonistas em um hospital, onde os médicos afirmam que ambos irão morrer. Eles têm poucas horas de vida. É um filme incrível, que quase faz com que o público sinta as rajadas de vento gelado do Atlântico, uma areia macia sob os pés e o cheiro do mar.',1997)
,('Os Bons Companheiros','O longa conta a história de Henry Hill, um gângster principiante que se dedica a roubar junto com Jimmy Convay e Tommy De Vito, que, com prazer, matam qualquer um que ficar no caminho da máfia. Filme muito realista sobre gângsters, com ótimos atores e bela cenografia, que tornam o filme hipnotizante.',1990)
,('O Grande Truque','Robert e Alfred são ilusionistas que competem entre si. Com o passar dos anos, a concorrência amistosa se transforma em verdadeira guerra. Os dois estão dispostas a tudo para roubar os segredos e frustrar os espetáculos um do outro. O ambiente da antiga Inglaterra, uma trama interessante e a mágica que tanto no fascina.',2006)
,('Pulp Fiction: Tempo de Violência','Dois delinquentes, Vincent Vega e Jules Winnfield, sempre que estão de folga de suas atividades criminosas, passam o tempo em conversas filosóficas. Filme obrigatório, cheio de estilo próprio e dirigido por Tarantino, um dos mais criativos cineastas da atualidade. A atuação de John Travolta é memorável.',1994)
,('O Resgate do Soldado Ryan','O capitão John Miller recebe uma tarefa pesada. Junto a um grupo de 8 pessoas, Miller deve ultrapassar as linhas inimigas em busca do soldado James Ryan. Obviamente, o filme é conhecido pelo realismo, pelo profundo significado e pelo trabalho incomparável de toda a equipe de filmagem. Com o sempre craque Tom Hanks.',1998)
,('Snatch: Porcos e Diamantes','Guy Ritchie é realmente um mestre do cinema. Já nas primeiras cenas, é possível perceber que este filme foi dirigido por ele. Além de seu grande trabalho como cineasta, o longa conta com ótimo elenco, com Brad Pitt e Benício del Toro. É uma obra-prima do cinema. Se você ainda não assistiu, assista. Você não vai se arrepender.',2000)
,('Os Suspeitos','Cinco criminosos se encontram num lugar incomum e combinam de praticar um crime. Mas alguém mais forte e poderoso, alguém cujo nome assusta a todos no mundo do crime, quer contratá-los. É um suspense de primeira, com elenco excelente e ótima trilha sonora.',1995)
,('Clube da Luta','Atormentado pela insônia crônica, um homem que tenta desesperadamente fugir de sua vida entediante conhece um tal de Tyler Durden, um vendedor de sabão muito carismático com uma filosofia de vida bem peculiar. O filme é uma adaptação do livro de Chuck Palahniuk, e já é considerado um clássico. Com Edward Norton e Brad Pitt.',1999)
,('Os Infiltrados','Dois dos melhores formados pela Academia de Polícia se veem em lados opostos: um deles é um agente da máfia que fazer parte da polícia, enquanto o outro é um espião infiltrado na máfia. Este é daqueles filmes que faz com que seu coração bata mais rápido. Você fica tão envolvido que a trama que, só quando os créditos sobem, é que se dá conta de que era apenas um filme',2006)
,('Interestelar','Quando uma seca no Planeta leva a humanidade a uma crise alimentícia, um grupo de pesquisadores e cientistas começa uma viagem para encontrar outro planeta que possa abrigar a humanidade. Filme grandioso, que conquistou muitos fãs.',2014);
;